[global]
; Server name (defaults to hostname capitalized)
; server_name=MARS
; Uncomment to take over existing IPX configurations
takeover_ipx=true
; Dump received RIP packets
;dump_rip = true
; Dump received SAP packets
;dump_sap = true
; Dump NCP events
dump_ncp = true
; Internal Network
internal_net = 0xF3F1F001
; Internal Node
;internal_node = AABBCC112233
; Organization (O=)
organization = MARSMINWE

; You will need to define at least one network section
[network]
; Mandatory
device=enp0s8
; Mandatory
frame=802.3
; Optional but faster (or required if no routers)
network=0xDEADBEEF

; To respond as a directory
[bindery]
; All there is atm because I Linux
source=pam
; User must be in this group to Netware 
group=mars

; Define at least one (and probably a SYS) volume 
[volume]
name=SYS
path=volumes/SYS
