[global]
; Uncomment to take over existing IPX configurations
takeover_ipx=true
; Dump received RIP packets
dump_rip = true
; Internal Network
internal_net = 0xF3F1F001
; Internal Node
internal_node = AABBCC112233

; You will need to define at least one network section
[network]
; Mandatory
device=enp0s8
; Mandatory
frame=802.3
; Optional but faster (or required if no routers)
network=0xDEADBEEF

